// SPDX-License-Identifier: GPL-3.0-or-later
package pf.ska987.patenteasy;
import android.app.*;
import android.text.InputType;
import android.widget.*;
import java.util.concurrent.ExecutorService;

/** Premier administrateur, connexion et récupération locale, sans serveur. */
final class Connexion {
    private final MainActivity activite;private final Coffre coffre;private final ExecutorService travail;
    Connexion(MainActivity a,Coffre c,ExecutorService e){activite=a;coffre=c;travail=e;}
    private EditText champ(LinearLayout l,String hint,boolean secret){EditText e=new EditText(activite);e.setHint(hint);e.setSingleLine(true);e.setInputType(secret?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_CLASS_TEXT);l.addView(e);return e;}
    void afficher(){boolean premier=!coffre.existe();LinearLayout l=new LinearLayout(activite);l.setOrientation(1);l.setPadding(32,16,32,16);
        TextView t=new TextView(activite);t.setText(premier?"Créez votre administrateur. Les données restent sur ce téléphone. Aucun accès pour ska_987.":"Ouvrez votre session locale.");l.addView(t);
        EditText id=champ(l,"Identifiant",false),password=champ(l,"Mot de passe (12 caractères minimum)",true),confirmation=premier?champ(l,"Confirmer le mot de passe",true):null;
        AlertDialog d=new AlertDialog.Builder(activite).setTitle(premier?"Bienvenue dans Patenteasy":"Connexion à Patenteasy").setView(l).setPositiveButton(premier?"Créer":"Se connecter",null).setNegativeButton("Fermer",(x,w)->activite.finish()).setNeutralButton(premier?"Restaurer":"Mot de passe oublié",null).create();d.setCancelable(false);d.setOnShowListener(v->{d.getButton(-1).setOnClickListener(w->{String ident=id.getText().toString(),mot=password.getText().toString();if(premier&&!mot.equals(confirmation.getText().toString())){t.setText("Les mots de passe diffèrent.");return;}d.getButton(-1).setEnabled(false);t.setText("Ouverture du coffre…");travail.execute(()->{try{String code=premier?coffre.creerAdmin(ident,mot):null;if(!premier)coffre.connexion(ident,mot);activite.runOnUiThread(()->{d.dismiss();if(code!=null)secours(code);else activite.ouvrir();});}catch(Exception e){activite.runOnUiThread(()->{t.setText(e.getMessage());d.getButton(-1).setEnabled(true);});}});});d.getButton(-3).setOnClickListener(w->{if(premier){d.dismiss();activite.choisirImport();}else{d.dismiss();recuperer();}});});d.show();
    }
    private void secours(String code){LinearLayout l=new LinearLayout(activite);l.setOrientation(1);l.setPadding(32,16,32,16);TextView t=new TextView(activite);t.setText("Conservez ce code dans un endroit privé. Il permet de récupérer votre compte administrateur. ska_987 n’en conserve aucune copie.");l.addView(t);TextView c=new TextView(activite);c.setText(code);c.setTextIsSelectable(true);c.setPadding(0,24,0,24);l.addView(c);CheckBox ok=new CheckBox(activite);ok.setText("J’ai conservé mon code de récupération");l.addView(ok);AlertDialog d=new AlertDialog.Builder(activite).setTitle("Votre code de récupération").setView(l).setPositiveButton("Continuer",null).create();d.setCancelable(false);d.setOnShowListener(v->{d.getButton(-1).setEnabled(false);ok.setOnCheckedChangeListener((b,x)->d.getButton(-1).setEnabled(x));d.getButton(-1).setOnClickListener(w->{d.dismiss();activite.ouvrir();});});d.show();}
    private void recuperer(){LinearLayout l=new LinearLayout(activite);l.setOrientation(1);l.setPadding(32,16,32,16);TextView t=new TextView(activite);t.setText("Administrateur : votre code de récupération est nécessaire. Utilisateur : demandez un nouveau compte à l’administrateur.");l.addView(t);EditText code=champ(l,"Code de récupération",true),mot=champ(l,"Nouveau mot de passe",true),confirmation=champ(l,"Confirmer",true);AlertDialog d=new AlertDialog.Builder(activite).setTitle("Récupérer mon compte").setView(l).setPositiveButton("Récupérer",null).setNegativeButton("Retour",(a,b)->afficher()).create();d.setCancelable(false);d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{if(!mot.getText().toString().equals(confirmation.getText().toString())){t.setText("Les mots de passe diffèrent.");return;}d.getButton(-1).setEnabled(false);travail.execute(()->{try{String nouveau=coffre.recuperer(code.getText().toString(),mot.getText().toString());activite.runOnUiThread(()->{d.dismiss();secours(nouveau);});}catch(Exception e){activite.runOnUiThread(()->{t.setText("Récupération impossible. Vérifiez votre code.");d.getButton(-1).setEnabled(true);});}});}));d.show();}
    void importer(android.net.Uri uri){LinearLayout l=new LinearLayout(activite);l.setOrientation(1);l.setPadding(32,16,32,16);TextView t=new TextView(activite);t.setText("Sur ce nouveau téléphone, importez votre sauvegarde Android avec le code de récupération correspondant. Les données Windows sont indépendantes.");l.addView(t);EditText code=champ(l,"Code de récupération",true),mot=champ(l,"Nouveau mot de passe administrateur",true),confirm=champ(l,"Confirmer",true);AlertDialog d=new AlertDialog.Builder(activite).setTitle("Restaurer sur ce téléphone").setView(l).setNegativeButton("Retour",(a,b)->afficher()).setPositiveButton("Restaurer",null).create();d.setCancelable(false);d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{String secret=code.getText().toString(),password=mot.getText().toString();if(!password.equals(confirm.getText().toString())){t.setText("Les mots de passe diffèrent.");return;}d.getButton(-1).setEnabled(false);travail.execute(()->{try{byte[] fichier=Coffre.lire(activite.getContentResolver().openInputStream(uri),20000000);String nouveau=coffre.restaurerNouveau(fichier,secret,password);activite.runOnUiThread(()->{d.dismiss();secours(nouveau);});}catch(Exception e){activite.runOnUiThread(()->{t.setText("Restauration impossible : "+e.getMessage());d.getButton(-1).setEnabled(true);});}});}));d.show();}

}
