// SPDX-License-Identifier: GPL-3.0-or-later
// Tests DOM sans navigateur ; pont natif et widgets Android simulés.
const {parseHTML}=require('linkedom'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {BaseLocale,GestionMobile,jour}=require('../app/src/main/assets/model.js');
const b=new BaseLocale(),g=new GestionMobile(b);g.entreprise({nom:'Atelier de Tahiti',adresse:'Papeete',tahiti:'TEST',rcs:'TEST',telephone:'',email:'',debut:'2020-01-01',regime:'franchise',confirme:true,validite:30,solde:0,dateSolde:jour(),vente:'Conditions',reglement:'Virement',mention:''});let c=g.client({nom:'Client test',adresse:'Tahiti',telephone:'',email:''});let q=g.devis({clientId:c,date:jour(),objet:'Réparation',validite:30,regime:'franchise',vente:'Conditions',reglement:'Virement',mention:'',lignes:[{reference:'MO',designation:'Main d’œuvre',unite:'heure',quantite:100,prix:250000,taux:0}]});g.emettre(q);g.decision(q,'accepte');g.facturer(q,jour(),jour());
let checks=0;
for(const role of ['admin','utilisateur']){
 const assets=path.resolve(__dirname,'../app/src/main/assets'),{window}=parseHTML(fs.readFileSync(path.join(assets,'index.html'),'utf8')),doc=window.document;
 window.HTMLElement.prototype.showModal=function(){this.setAttribute('open','');};window.HTMLElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new window.Event('close'));};
 Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){const o=this.querySelector('option[selected]')||this.querySelector('option');return o?o.value:'';},set(v){for(const o of this.querySelectorAll('option')){o.toggleAttribute('selected',o.value===v);}}});
 Object.defineProperty(window.HTMLElement.prototype,'elements',{configurable:true,get(){const arr=Array.from(this.querySelectorAll('input,select,textarea'));for(const e of arr)arr[e.getAttribute('name')]=e;return arr;}});
 class FormData {constructor(f){this.a=[];for(const e of f.querySelectorAll('input,select,textarea')){const n=e.getAttribute('name');if(n&&!(e.type==='checkbox'&&!e.checked))this.a.push([n,e.value]);}}get(n){return this.a.find(x=>x[0]===n)?.[1];}[Symbol.iterator](){return this.a[Symbol.iterator]();}}
 let donnees=JSON.parse(JSON.stringify(b.donnees)),preferences={theme:'clair',accent:'#285b9b',verrouillage:15};const ok=valeur=>JSON.stringify({ok:true,valeur});
 window.Android={charger:()=>JSON.stringify(donnees),sauver:s=>{donnees=JSON.parse(s);return true;},session:()=>ok({identifiant:role==='admin'?'mika':'employe',role,preferences}),configuration:()=>JSON.stringify({paypal_url:'https://www.paypal.com/ncp/payment/A3ELC2Q8GM82N',telechargements_url:'https://drive.proton.me/urls/ZD87JFPW44#kdecNnhPndLG'}),bienvenueVue:()=>true,marquerBienvenue:()=>true,sauvegardeEtat:()=>ok({configure:true,derniere:Date.now(),erreur:''}),miseAJourEtat:()=>ok({nouvelle:true,version:'0.3.7'}),comptes:()=>ok([{identifiant:'mika',role:'admin',actif:true},{identifiant:'employe',role:'utilisateur',actif:true}]),journalAcces:()=>ok([]),preferences:s=>{preferences=JSON.parse(s);return ok(true);},motDePasse:()=>ok(true),sauvegarder:()=>{},verifierMiseAJour:()=>{},creerCompte:()=>ok(true),activer:()=>ok(true),deconnexion:()=>{},pdf:()=>{},partagerPdf:()=>{},exportCsv:()=>{}};
 const sandbox={window,document:doc,console,Intl,Date,URL,URLSearchParams,FormData,setInterval:()=>1,setTimeout:()=>1,localStorage:{getItem:()=>null,setItem:()=>{}},location:{href:''},confirm:()=>true,prompt:()=>null};const ctx=vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(assets,'model.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(path.join(assets,'app.js'),'utf8'),ctx);
 vm.runInContext(fs.readFileSync(path.join(assets,'beta.js'),'utf8'),ctx);
 const content=()=>doc.getElementById('contenu').textContent;const evalJS=s=>vm.runInContext(s,ctx);
 assert.match(doc.getElementById('session').textContent,role==='admin'?/Administrateur/:/Utilisateur/);checks++;
 if(role==='admin'){assert.match(content(),/Recettes/);checks++;}else{assert.doesNotMatch(content(),/Recettes|Trésorerie|Dépenses/);assert.equal(doc.querySelector('[data-page=entreprise]').hidden,true);evalJS('interfaceMobile.journal()');assert.match(content(),/Régler un fournisseur/);assert.doesNotMatch(content(),/Opérations/);evalJS('interfaceMobile.factures()');doc.querySelector('input[name=numero]').value='fact-D-00001';doc.getElementById('recherche').onsubmit({preventDefault(){},target:doc.getElementById('recherche')});assert.match(content(),/Reste à encaisser/);assert.equal(doc.getElementById('avoir'),null);assert.equal(evalJS("(()=>{try{gestion.avoir('x','test');return false;}catch(e){return /administrateur/.test(e.message);}})()"),true);checks+=6;}
 evalJS('interfaceMobile.reglages()');assert.equal(!!doc.getElementById('creer-compte'),role==='admin');assert.equal(!!doc.getElementById('restaurer'),role==='admin');assert.equal(!!doc.getElementById('installer-update'),role==='admin');checks+=3;
 doc.querySelector('#preferences select').value='sombre';doc.getElementById('preferences').onsubmit({preventDefault(){},target:doc.getElementById('preferences')});assert.equal(doc.documentElement.dataset.theme,'sombre');checks++;
 assert.equal(content().includes('Exporter les recettes et dépenses en CSV'),role==='admin');checks++;
 evalJS('interfaceMobile.clients()');const filtre=doc.querySelector('input[type=search]');assert.ok(filtre);filtre.value='introuvable';filtre.oninput();assert.ok(Array.from(doc.getElementById('liste').children).every(r=>r.hidden));checks+=2;
 evalJS('interfaceMobile.factures()');assert.equal(!!doc.querySelector('input[type=search]'),role==='admin');checks++;
 if(role==='admin'){evalJS('OutilsBeta.demarrage()');assert.match(content(),/Bien démarrer/);checks++;}
 assert.ok(doc.getElementById('backup-notice').hidden);checks++;
 evalJS('demanderNouveautes()');assert.equal(doc.getElementById('dialog-stats').hasAttribute('checked'),false);assert.equal(doc.getElementById('dialog-news').hasAttribute('checked'),false);checks+=2;
 for(const methode of ['clients','catalogue','devis','aide'])evalJS('interfaceMobile.'+methode+'()');assert.doesNotMatch(doc.getElementById('message').textContent,/impossible|invalide/i);checks++;
}
console.log(checks+' contrôles DOM réussis (interface et pont Android simulés ; pas de rendu sur téléphone).');
