// SPDX-License-Identifier: GPL-3.0-or-later
// Interface WebView testée dans Chromium avec pont Android simulé.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
const {BaseLocale,GestionMobile,jour}=require('../app/src/main/assets/model.js');
const base=new BaseLocale(),g=new GestionMobile(base);g.entreprise({nom:'Atelier de Tahiti',adresse:'Papeete',tahiti:'TEST',rcs:'TEST',telephone:'',email:'',debut:'2020-01-01',regime:'franchise',confirme:true,validite:30,solde:0,dateSolde:jour(),vente:'Conditions de vente',reglement:'Virement',mention:''});let c=g.client({nom:'Client test',adresse:'Tahiti',telephone:'',email:''});let q=g.devis({clientId:c,date:jour(),objet:'Réparation',validite:30,regime:'franchise',vente:'Conditions',reglement:'Virement',mention:'',lignes:[{reference:'MO',designation:'Main d’œuvre',unite:'heure',quantite:100,prix:250000,taux:0}]});g.emettre(q);g.decision(q,'accepte');let f=g.facturer(q,jour(),jour());
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.PATENTEASY_CHROME||undefined,args:['--no-sandbox','--no-zygote','--single-process','--disable-gpu','--no-process-singleton']});let checks=0;
 for(const role of ['admin','utilisateur']){const p=await browser.newPage({viewport:{width:412,height:915}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(({data,role})=>{let preferences={theme:'clair',accent:'#285b9b',verrouillage:15};const ok=valeur=>JSON.stringify({ok:true,valeur});window.Android={charger:()=>JSON.stringify(data),sauver:s=>{data=JSON.parse(s);return true;},session:()=>ok({identifiant:role==='admin'?'mika':'employe',role,preferences}),configuration:()=>JSON.stringify({paypal_url:'https://www.paypal.com/ncp/payment/A3ELC2Q8GM82N',telechargements_url:'https://drive.proton.me/urls/ZD87JFPW44#kdecNnhPndLG'}),bienvenueVue:()=>true,marquerBienvenue:()=>true,sauvegardeEtat:()=>ok({configure:true,derniere:Date.now(),erreur:''}),miseAJourEtat:()=>ok({nouvelle:true,version:'0.3.7'}),comptes:()=>ok([{identifiant:'mika',role:'admin',actif:true},{identifiant:'employe',role:'utilisateur',actif:true}]),journalAcces:()=>ok([]),preferences:s=>{preferences=JSON.parse(s);return ok(true);},motDePasse:()=>ok(true),sauvegarder:()=>{},verifierMiseAJour:()=>{},creerCompte:()=>ok(true),activer:()=>ok(true),deconnexion:()=>{},pdf:()=>{},partagerPdf:()=>{}};},{data:base.donnees,role});await p.goto('file://'+path.resolve(__dirname,'../app/src/main/assets/index.html'));await p.waitForSelector('#societe');assert.equal(errors.length,0,errors.join('\n'));checks++;
 if(role==='admin'){assert.match(await p.locator('#contenu').innerText(),/Recettes/);await p.screenshot({path:path.resolve(__dirname,'../../aperçu-admin-clair.png'),fullPage:true});}else{assert.doesNotMatch(await p.locator('#contenu').innerText(),/Recettes|Trésorerie|Dépenses/);assert.equal(await p.locator('[data-page=entreprise]').isVisible(),false);await p.click('[data-page=journal]');assert.match(await p.locator('#contenu').innerText(),/Régler un fournisseur/);assert.doesNotMatch(await p.locator('#contenu').innerText(),/Opérations/);await p.click('[data-page=factures]');await p.fill('input[name=numero]','fact-D-00001');await p.click('#recherche button');assert.match(await p.locator('#contenu').innerText(),/Reste à encaisser/);assert.equal(await p.locator('#avoir').count(),0);const guard=await p.evaluate(()=>{try{gestion.avoir('f','test');return false;}catch(e){return /administrateur/.test(e.message);}});assert.equal(guard,true);checks+=5;await p.evaluate(()=>interfaceMobile.accueilUtilisateur());await p.screenshot({path:path.resolve(__dirname,'../../aperçu-utilisateur.png'),fullPage:true});}
 await p.click('#ouvrir-reglages');assert.equal(await p.locator('#creer-compte').count(),role==='admin'?1:0);assert.equal(await p.locator('#restaurer').count(),role==='admin'?1:0);assert.equal(await p.locator('#installer-update').count(),role==='admin'?1:0);checks+=3;await p.selectOption('#preferences select','sombre');await p.click('#preferences button');assert.equal(await p.locator('html').getAttribute('data-theme'),'sombre');checks++;await p.screenshot({path:path.resolve(__dirname,'../../aperçu-'+role+'-sombre.png'),fullPage:true});await p.evaluate(()=>demanderNouveautes());assert.equal(await p.locator('#dialog-stats').isChecked(),false);assert.equal(await p.locator('#dialog-news').isChecked(),false);checks+=2;await p.click('#dialog-cancel');assert.equal(errors.length,0,errors.join('\n'));await p.close();
 }await browser.close();console.log(checks+' contrôles de l’interface réussis (Chromium, pont Android simulé).');})().catch(e=>{console.error(e);process.exitCode=1;});
