// SPDX-License-Identifier: GPL-3.0-or-later
const {test}=require('node:test');const assert=require('node:assert/strict');
const {BaseLocale,GestionMobile,totaux,jour}=require('../app/src/main/assets/model.js');
function atelier(regime='franchise',sauver=()=>{}){const b=new BaseLocale(null,sauver),g=new GestionMobile(b);g.entreprise({nom:'Atelier',adresse:'Moorea',tahiti:'TEST',rcs:'',telephone:'',email:'',debut:'2020-01-01',regime,confirme:true,validite:30,solde:0,dateSolde:jour(),vente:'Conditions',reglement:'Virement',mention:''});const c=g.client({nom:'Client',adresse:'Tahiti',telephone:'',email:''});const q=g.devis({clientId:c,date:jour(),objet:'Réparation',validite:30,regime,vente:'Conditions',reglement:'Virement',mention:'',lignes:[{reference:'MO',designation:'Main d’œuvre',unite:'heure',quantite:150,prix:350000,taux:1300}]});return {b,g,c,q};}
test('Premier lancement réellement vide',()=>{const b=new BaseLocale();assert.equal(b.donnees.entreprise,null);assert.equal(b.donnees.factures.length,0);});
test('Devis accepté, facture unique, paiement et avoir',()=>{const {b,g,q}=atelier();g.emettre(q);assert.equal(b.donnees.devis[0].instantane.numero,'dev-D-00001');assert.throws(()=>g.facturer(q,jour(),jour()));g.decision(q,'accepte');const f=g.facturer(q,jour(),jour());assert.equal(b.donnees.factures[0].instantane.numero,'fact-D-00001');assert.throws(()=>g.facturer(q,jour(),jour()));assert.throws(()=>g.devis({...b.donnees.devis[0]},q));g.paiement(f,jour(),200000,'virement');assert.equal(g.reste(b.donnees.factures[0]),325000);assert.equal(b.donnees.journal.length,1);assert.throws(()=>g.paiement(f,jour(),400000,'virement'));g.avoir(f,'Annulation');assert.equal(g.reste(b.donnees.factures[0]),0);assert.throws(()=>g.avoir(f,'Encore'));});
test('TVA et arrondis entiers',()=>{const {g,b,q}=atelier('reel');g.emettre(q);assert.equal(b.donnees.devis[0].instantane.totaux.tva,68250);assert.equal(totaux([{designation:'Ligne',unite:'u',quantite:1,prix:50,taux:0}],'franchise').ht,1);});
test('Échec du stockage annule aussi le numéro',()=>{let erreur=false;const {b,g,q}=atelier('franchise',()=>{if(erreur)throw Error('Disque plein');});erreur=true;assert.throws(()=>g.emettre(q));assert.equal(b.donnees.sequences.dev,0);assert.equal(b.donnees.devis[0].statut,'brouillon');});
test('Sauvegarde ancienne refusée, sauvegarde corrompue refusée',()=>{const {b,g,q}=atelier();const ancienne=JSON.parse(JSON.stringify(b.donnees));g.emettre(q);assert.throws(()=>b.restaurer(ancienne));const copie=JSON.parse(JSON.stringify(b.donnees));copie.devis[0].instantane.totaux.ttc=0;assert.throws(()=>b.restaurer(copie));const neuf=new BaseLocale();neuf.restaurer(b.donnees);assert.equal(neuf.donnees.devis[0].instantane.numero,'dev-D-00001');});
test('Identité émise figée et numéro suivant après duplication',()=>{const {b,g,q}=atelier();g.emettre(q);g.entreprise({...b.donnees.entreprise,nom:'Autre nom'});assert.equal(b.donnees.devis[0].instantane.entreprise.nom,'Atelier');const q2=g.dupliquer(q);g.emettre(q2);assert.equal(b.donnees.devis[1].instantane.numero,'dev-D-00002');});


test('Profil facultatif et conditions rétroactives sans mutation financière',()=>{const {b,g,q}=atelier();g.emettre(q);g.decision(q,'accepte');const f=g.facturer(q,jour(),jour());const avant=JSON.stringify(b.donnees.factures[0]);g.conditions({reglement:'Nouvelle règle',vente:'',mention:'Option'});assert.equal(b.donnees.entreprise.reglement,'Nouvelle règle');assert.equal(JSON.stringify(b.donnees.factures[0]),avant);const recharge=new BaseLocale(JSON.parse(JSON.stringify(b.donnees)));assert.equal(recharge.donnees.entreprise.reglement,'Nouvelle règle');});
test('Nouveau profil mondial et devis incomplet conservé',()=>{const b=new BaseLocale(),g=new GestionMobile(b);g.entreprise({nom:'Design studio',pays:'CA',devise:'CAD',decimales:2,regime:'',validite:30});const id=g.devis({clientId:'',date:'12/',validite:30,regime:'',lignes:[]});assert.equal(new BaseLocale(JSON.parse(JSON.stringify(b.donnees))).donnees.devis[0].date,'12/');assert.throws(()=>g.emettre(id));const c=g.client({nom:'Premier client'});g.devis({clientId:c,date:jour(),validite:30,regime:'',lignes:[{reference:'REF',designation:'Service',unite:'u',quantite:100,prix:1234,taux:2000}]},id);g.emettre(id);g.decision(id,'accepte');const f=g.facturer(id,jour(),jour());g.paiement(f,jour(),1234,'especes');assert.equal(g.reste(b.donnees.factures[0]),0);assert.equal(b.donnees.factures[0].instantane.totaux.tva,0);});
test('Identité et devise historiques protégées',()=>{const {b,g,q}=atelier();g.emettre(q);g.decision(q,'accepte');g.entreprise({...b.donnees.entreprise,nom:'Nouvelle identité'});g.facturer(q,jour(),jour());assert.equal(b.donnees.factures[0].instantane.entreprise.nom,'Atelier');assert.throws(()=>g.entreprise({...b.donnees.entreprise,devise:'EUR',decimales:2}));});
